# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20170411_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='alldesc',
            field=models.CharField(default='', max_length=300, verbose_name='\u8bfe\u7a0b\u516c\u544a'),
        ),
    ]
